[package]
name = "kanjida"
version = "0.1.0"
edition = "2021"

[dependencies]
aframers = { git = "https://github.com/wehjin/aframers.git", version = "0.1.0" }
anyhow = "1.0.86"
console_error_panic_hook = "0.1.7"
wasm-bindgen = "0.2.92"
web-sys = { version = "0.3.69", features = ["Window", "Document", "HtmlElement", "Text"] }
